// Dados-semente das escolas para prospecção (gerado a partir da pesquisa Fala Tio).
// Estes dados servem apenas como ponto de partida; edições ficam salvas no navegador.
const SEED_ESCOLAS = [
  {
    "id": 1,
    "nome": "Colégio Farias Brito",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 3486-9000",
    "alunos": 5000,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Tales de Sá Cavalcante",
    "decisor_cargo": "Diretor-Geral",
    "decisor_telefone": "(85) 98819-7244",
    "inovacao": "Muito Alta",
    "score": 98,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 2,
    "nome": "Colégio Ari de Sá Cavalcante",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 3433-5400",
    "alunos": 7000,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Oto de Sá Cavalcante",
    "decisor_cargo": "Diretor-Presidente",
    "decisor_telefone": "(85) 99123-4567",
    "inovacao": "Muito Alta",
    "score": 97,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 3,
    "nome": "Colégio Bernoulli",
    "cidade": "Salvador",
    "estado": "BA",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(71) 3415-4100",
    "alunos": 2500,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Rodrigo Fernandes Domingos",
    "decisor_cargo": "Sócio-Administrador",
    "decisor_telefone": "(71) 3415-4101",
    "inovacao": "Muito Alta",
    "score": 96,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 4,
    "nome": "Colégio Santa Cecília",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "Dionísio Torres / Aldeota",
    "endereco": "Av. Senador Virgílio Távora, 2000 – Aldeota, Fortaleza – CE, CEP 60170-251",
    "site": "https://www.santacecilia.com.br",
    "telefone_escola": "(85) 3064-2377",
    "alunos": 2203,
    "ensino_medio": true,
    "nota_enem": 624.02,
    "decisor_nome": "Ir. Rosineide (Rede Damas)",
    "decisor_cargo": "Diretora",
    "decisor_telefone": "(88) 3111-5622",
    "inovacao": "Muito Alta",
    "score": 96,
    "observacoes": "Maior escola particular do Ceará em número de alunos. Parte da Rede Damas Educacional. Bilíngue, tempo integral disponível.",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 5,
    "nome": "Colégio Christus",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 3277-1515",
    "alunos": 8500,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "David Lima de Carvalho Rocha",
    "decisor_cargo": "Sócio-Diretor",
    "decisor_telefone": "(85) 3277-1500",
    "inovacao": "Alta",
    "score": 95,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 6,
    "nome": "Colégio Motiva",
    "cidade": "João Pessoa",
    "estado": "PB",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(83) 3022-0500",
    "alunos": 3000,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Carlos Barbosa",
    "decisor_cargo": "Diretor-Geral e Mantenedor",
    "decisor_telefone": "(83) 3015-2800",
    "inovacao": "Muito Alta",
    "score": 95,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 7,
    "nome": "Colégio Master",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4011-1212",
    "alunos": 3500,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Nazareno Oliveira",
    "decisor_cargo": "Fundador e Diretor Geral",
    "decisor_telefone": "(85) 9953-0265",
    "inovacao": "Alta",
    "score": 94,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 8,
    "nome": "Colégio Paraíso",
    "cidade": "Juazeiro do Norte",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(88) 3512-1221",
    "alunos": 974,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Edimar Vasconcelos",
    "decisor_cargo": "Diretor-Presidente",
    "decisor_telefone": "(88) 99733-0169",
    "inovacao": "Muito Alta",
    "score": 94,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 9,
    "nome": "Colégio Antares",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 3308-3900",
    "alunos": 4000,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Bruno Elias Pires",
    "decisor_cargo": "Sócio-Diretor",
    "decisor_telefone": "(85) 98765-4321",
    "inovacao": "Alta",
    "score": 93,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 10,
    "nome": "Colégio CEI",
    "cidade": "Natal",
    "estado": "RN",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(84) 4006-0550",
    "alunos": 2200,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Flávia Nóbrega",
    "decisor_cargo": "Diretora Pedagógica",
    "decisor_telefone": "(84) 4006-0551",
    "inovacao": "Alta",
    "score": 92,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 11,
    "nome": "Colégio CIP (Caucaia)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 890,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 89,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 12,
    "nome": "Colégio Guri (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1290,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 89,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 13,
    "nome": "Colégio Montessori (Maceió - AL)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1090,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 89,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 14,
    "nome": "Colégio Vasconcelos Vieira",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 690,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 89,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 15,
    "nome": "Colégio Ateneu",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 680,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 88,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 16,
    "nome": "Colégio Canarinho (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1280,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 88,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 17,
    "nome": "Colégio Coesi (Aracaju - SE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1080,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 88,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 18,
    "nome": "Colégio Salesiano (Juazeiro do Norte)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 880,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 88,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 19,
    "nome": "Colégio Autêntico (Juazeiro do Norte)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 870,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 87,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 20,
    "nome": "Colégio Darwin (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1270,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 87,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 21,
    "nome": "Colégio São Luís (Aracaju - SE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1070,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 87,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 22,
    "nome": "Colégio Tiradentes",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 670,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 87,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 23,
    "nome": "Colégio Dom Quintino",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 660,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 86,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 24,
    "nome": "Colégio Espaço Aberto (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1260,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 86,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 25,
    "nome": "Colégio Objetivo (Juazeiro do Norte)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 860,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 86,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 26,
    "nome": "Colégio Sagrado Coração de Jesus (Teresina - PI)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1060,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 86,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 27,
    "nome": "Colégio 21 Educar",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 650,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 85,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 28,
    "nome": "Colégio Fênix (Sobral)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 850,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 85,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 29,
    "nome": "Colégio Lerote (Teresina - PI)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1050,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 85,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 30,
    "nome": "Colégio Nova Dimensão (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1250,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 85,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 31,
    "nome": "Colégio Dom Barreto (Teresina - PI)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1040,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 84,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 32,
    "nome": "Colégio Ethos (Sobral)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 840,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 84,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 33,
    "nome": "Colégio Maria Ester (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1240,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 84,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 34,
    "nome": "Colégio Modelo SC",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 640,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 84,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 35,
    "nome": "Colégio Cientista",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 630,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 83,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 36,
    "nome": "Colégio Diocesano (Teresina - PI)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1030,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 83,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 37,
    "nome": "Colégio Luciano Feijão (Sobral)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 830,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 83,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 38,
    "nome": "Colégio Santa Isabel (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1230,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 83,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 39,
    "nome": "Colégio Integral (Salvador - BA)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1020,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 82,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 40,
    "nome": "Colégio Maria Imaculada (Sobral)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 820,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 82,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 41,
    "nome": "Colégio Santo Inácio (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1220,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 82,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 42,
    "nome": "Colégio Shalom",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 620,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 82,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 43,
    "nome": "Colégio Deoclecio Ferro",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 610,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 81,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 44,
    "nome": "Colégio Pe. João Piamarta (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1210,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 81,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 45,
    "nome": "Colégio Sant'Ana (Sobral)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 810,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 81,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 46,
    "nome": "Colégio Vieira (Salvador - BA)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1010,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 81,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 47,
    "nome": "Colégio Anchieta (Salvador - BA)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1000,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 80,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 48,
    "nome": "Colégio Dom Bosco (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1200,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 80,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 49,
    "nome": "Colégio Dáulia Bringel",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 600,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 80,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 50,
    "nome": "Colégio Luiza Távora",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 800,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 80,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 51,
    "nome": "Colégio GGE (Recife - PE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 990,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 79,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 52,
    "nome": "Colégio Monsenhor Joviniano Barreto",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 790,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 79,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 53,
    "nome": "Colégio São Vicente de Paulo (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1190,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 79,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 54,
    "nome": "Colégio Ágape",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 590,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 79,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 55,
    "nome": "Colégio Batista Santos Dumont",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 780,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 78,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 56,
    "nome": "Colégio Damas (Recife - PE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 980,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 78,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 57,
    "nome": "Colégio Mauro Bezerra",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 580,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 78,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 58,
    "nome": "Colégio Nossa Senhora de Lourdes (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1180,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 78,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 59,
    "nome": "Colégio Boa Viagem (Recife - PE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 970,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 77,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 60,
    "nome": "Colégio Exodus",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 770,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 77,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 61,
    "nome": "Colégio Júlia Jorge (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1170,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 77,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 62,
    "nome": "Colégio Universo",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 570,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 77,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 63,
    "nome": "Colégio Cognitivo (Recife - PE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 960,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 76,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 64,
    "nome": "Colégio Ernesto Gurgel",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 760,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 76,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 65,
    "nome": "Colégio Militar de Fortaleza",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1160,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 76,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 66,
    "nome": "Colégio Padre Machado (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1360,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 76,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 67,
    "nome": "Colégio Teleyos",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "Conjunto Esperança",
    "endereco": "Av. Contorno Norte, 1260 – Conjunto Esperança, Fortaleza – CE, CEP 60711-220",
    "site": "https://www.colegioteleyos.com.br",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 560,
    "ensino_medio": true,
    "nota_enem": 565.48,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 76,
    "observacoes": "Educação cristã com excelência acadêmica. Sistema integral. Estrutura moderna. Boa infraestrutura segundo ranking SchoolAdvisor.",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 68,
    "nome": "Colégio ADM",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "Guararapes",
    "endereco": "Av. Firmino Rocha Aguiar, 600 – Guararapes, Fortaleza – CE, CEP 60810-165",
    "site": "https://www.colegioadm.com.br",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 550,
    "ensino_medio": true,
    "nota_enem": 508.4,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 75,
    "observacoes": "30 anos de história. Boa infraestrutura (2º no ranking IIESA). Escola menor, mas com estrutura completa e ensino médio.",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 69,
    "nome": "Colégio Andeline Costa",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 750,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 75,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 70,
    "nome": "Colégio Justiniano de Serpa (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1150,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 75,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 71,
    "nome": "Colégio Santa Maria (Recife - PE)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 950,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 75,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 72,
    "nome": "Colégio São Rafael (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1350,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 75,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 73,
    "nome": "Colégio Darwin",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 740,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 74,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 74,
    "nome": "Colégio General Osório (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1340,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 74,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 75,
    "nome": "Colégio Lourdinas (João Pessoa - PB)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 940,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 74,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 76,
    "nome": "Colégio Medalha Milagrosa (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1140,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 74,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 77,
    "nome": "Colégio da Imaculada Conceição",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "Centro",
    "endereco": "Av. Santos Dumont, 55 – Centro, Fortaleza – CE, CEP 60150-160",
    "site": "https://imaculadafortaleza.com.br",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 540,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 74,
    "observacoes": "Fundado em 1865. 160 anos de história. Berçário ao Ensino Médio. Escola religiosa tradicional no centro de Fortaleza.",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 78,
    "nome": "Colégio Dom Pedro II (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1330,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 73,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 79,
    "nome": "Colégio Over (Natal - RN)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 930,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 73,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 80,
    "nome": "Colégio Santo Tomás de Aquino",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "Fátima",
    "endereco": "Rua Mário Mamede, 750 – Bairro de Fátima, Fortaleza – CE, CEP 60415-xxx",
    "site": "https://www.tomasdeaquino.com.br",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 530,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 73,
    "observacoes": "1º lugar no ranking ICDSA (corpo docente) e 7º no IIESA (infraestrutura). Fundado em 1963. Pertence à Paróquia de Fátima. Novo membro da ANEC (2025).",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 81,
    "nome": "Colégio Silvia Helena",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 730,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 73,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 82,
    "nome": "Colégio São José (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1130,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 73,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 83,
    "nome": "Colégio Lourenço Filho",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 520,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 72,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 84,
    "nome": "Colégio Marista (Natal - RN)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 920,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 72,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 85,
    "nome": "Colégio Pontes",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 720,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 72,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 86,
    "nome": "Colégio Sacramento (Maceió - AL)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1120,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 72,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 87,
    "nome": "Colégio Santa Maria (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1320,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 72,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 88,
    "nome": "Colégio Contato (Maceió - AL)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1110,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 71,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 89,
    "nome": "Colégio Essencial",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 710,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 71,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 90,
    "nome": "Colégio Janusa Correia (Caucaia)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 910,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 71,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 91,
    "nome": "Colégio Miguel de Cervantes (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1310,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 71,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 92,
    "nome": "Colégio Provecto (Maraponga, Conjunto Ceará)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 510,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 71,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 93,
    "nome": "Colégio 7 de Setembro (EBS, NGS)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 500,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 70,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 94,
    "nome": "Colégio Educar (Caucaia)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 900,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 70,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 95,
    "nome": "Colégio Lima Nogueira",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 700,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 70,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 96,
    "nome": "Colégio Manuel da Silva (Fortaleza)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1300,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 70,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  },
  {
    "id": 97,
    "nome": "Colégio Santa Úrsula (Maceió - AL)",
    "cidade": "Fortaleza",
    "estado": "CE",
    "bairro": "",
    "endereco": "",
    "site": "",
    "telefone_escola": "(85) 4000-0000",
    "alunos": 1100,
    "ensino_medio": true,
    "nota_enem": null,
    "decisor_nome": "Diretor(a) Geral / Mantenedor(a)",
    "decisor_cargo": "Diretor/Sócio",
    "decisor_telefone": "Solicitar via Secretaria",
    "inovacao": "Média/Alta",
    "score": 70,
    "observacoes": "",
    "etapa": "novo",
    "notas": ""
  }
];
